In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('singapore_metro_stations.csv')

In [3]:
df.shape

(171, 7)

In [4]:
df.head()

,Unnamed: 0,OBJECTID,STN_NAME,STN_NO,geometry,Latitude,Longitude
0,0,1,EUNOS MRT STATION,EW7,POINT (103.9032524667383 1.319778951553637),1.319779,103.903252
1,1,2,CHINESE GARDEN MRT STATION,EW25,POINT (103.7325967380734 1.342352820874744),1.342353,103.732597
2,2,3,KHATIB MRT STATION,NS14,POINT (103.8329799077383 1.417383370153547),1.417383,103.832980
3,3,4,KRANJI MRT STATION,NS7,POINT (103.7621654109002 1.425177698770448),1.425178,103.762165
4,4,5,REDHILL MRT STATION,EW18,POINT (103.816816670149 1.289562726402453),1.289563,103.816817

In [5]:
df_stations = pd.DataFrame()

In [7]:
df_stations['name'] = df['STN_NAME']

In [8]:
df_stations['code'] = df['STN_NO']

In [9]:
df_stations.head()

                         name  code
0           EUNOS MRT STATION   EW7
1  CHINESE GARDEN MRT STATION  EW25
2          KHATIB MRT STATION  NS14
3          KRANJI MRT STATION   NS7
4         REDHILL MRT STATION  EW18

In [13]:
df_stations['name'] = df_stations['name'].map(lambda station : station.replace(" STATION", ""))

In [14]:
df_stations.head()

                 name  code
0           EUNOS MRT   EW7
1  CHINESE GARDEN MRT  EW25
2          KHATIB MRT  NS14
3          KRANJI MRT   NS7
4         REDHILL MRT  EW18

In [15]:
df_stations['type'] = df_stations['name'].map(lambda station : station.split(' ')[-1])

In [16]:
df_stations.head()

                 name  code type
0           EUNOS MRT   EW7  MRT
1  CHINESE GARDEN MRT  EW25  MRT
2          KHATIB MRT  NS14  MRT
3          KRANJI MRT   NS7  MRT
4         REDHILL MRT  EW18  MRT

In [17]:
df_stations['type'].unique()

array(['MRT', 'LRT'], dtype=object)

In [18]:
df_stations['name'] = df_stations['name'].map(lambda station : station.replace(" MRT", ""))

In [19]:
df_stations['name'] = df_stations['name'].map(lambda station : station.replace(" LRT", ""))

In [20]:
df_stations.head()

             name  code type
0           EUNOS   EW7  MRT
1  CHINESE GARDEN  EW25  MRT
2          KHATIB  NS14  MRT
3          KRANJI   NS7  MRT
4         REDHILL  EW18  MRT

In [25]:
new_lines = []
lines = df_stations.values
for line in lines:
    codes = line[1].split('/')
    if len(codes) > 1:
        for code in codes:
            new_lines.append([line[0], code, line[2]])
    else:
        new_lines.append(line)

In [26]:
len(lines)

171

In [27]:
len(new_lines)

197

In [28]:
df_stations = pd.DataFrame(new_lines)

In [29]:
df_stations.head()

                0     1    2
0           EUNOS   EW7  MRT
1  CHINESE GARDEN  EW25  MRT
2          KHATIB  NS14  MRT
3          KRANJI   NS7  MRT
4         REDHILL  EW18  MRT

In [30]:
df_stations.columns = ['name', 'code', 'type']

In [31]:
df_stations.head()

             name  code type
0           EUNOS   EW7  MRT
1  CHINESE GARDEN  EW25  MRT
2          KHATIB  NS14  MRT
3          KRANJI   NS7  MRT
4         REDHILL  EW18  MRT

In [32]:
df_stations['line'] = None

In [33]:
df_stations['serial'] = None

In [42]:
df_stations['code'].unique()

array(['EW7', 'EW25', 'NS14', 'NS7', 'EW18', 'NS5', 'EW28', 'EW20', 'EW8',
       'CC9', 'EW3', 'EW2', 'DT32', 'NS10', 'NS13', 'EW1', 'EW23', 'EW9',
       'NS16', 'CG1', 'DT35', 'NS4', 'EW24', 'NS1', 'EW19', 'EW33',
       'EW30', 'NS9', 'TE2', 'EW31', 'EW10', 'EW32', 'EW21', 'CC22',
       'EW22', 'NS11', 'EW6', 'NS2', 'EW27', 'NS3', 'NS8', 'EW5', 'EW29',
       'EW26', 'EW4', 'NS15', 'CC2', 'CC10', 'DT26', 'EW13', 'NS25',
       'DT33', 'DT31', 'DT24', 'DT23', 'DT21', 'NE1', 'CC29', 'CC24',
       'NE17', 'EW15', 'CC23', 'CC6', 'EW12', 'DT14', 'NS23', 'NS22',
       'TE14', 'DT22', 'DT16', 'CE1', 'NE16', 'CC18', 'CC7', 'NE13',
       'DT20', 'CC20', 'DT17', 'CC3', 'CC5', 'CC17', 'TE9', 'NS27',
       'TE20', 'CE2', 'CC27', 'NE4', 'DT19', 'DT8', 'EW17', 'DT3', 'DT6',
       'DT25', 'DT27', 'DT5', 'DT28', 'DT29', 'NS24', 'NE6', 'CC1',
       'NE11', 'NS20', 'NE12', 'CC13', 'DT30', 'NS28', 'NE8', 'CC12',
       'CC8', 'CC26', 'NE5', 'NS17', 'CC15', 'CC16', 'CC25', 'CC14',
       'EW11', 'CC11', 'DT13', 'NE7', 'DT12', 'DT10', 'TE11', 'DT1',
       'DT2', 'DT7', 'NS19', 'TE3', 'NE10', 'NE14', 'NE9', 'DT34', 'CG2',
       'NS18', 'NE15', 'CC4', 'DT15', 'CC19', 'DT9', 'EW14', 'NS26',
       'CC21', 'EW16', 'CC28', 'DT18', 'NS21', 'DT11', 'NS12', 'TE1',
       'DT4', 'TE4', 'TE5', 'TE6', 'TE7', 'TE8'], dtype=object)

In [40]:
df_stations = df_stations[df_stations['type'] != 'LRT']

In [41]:
df_stations['type'].unique()

array(['MRT'], dtype=object)

In [43]:
import re

In [45]:
df_stations['line'] = df_stations['code'].map(lambda code : re.findall('[A-Z]+', code)[0])

In [46]:
df_stations.head()

             name  code type line serial
0           EUNOS   EW7  MRT   EW   None
1  CHINESE GARDEN  EW25  MRT   EW   None
2          KHATIB  NS14  MRT   NS   None
3          KRANJI   NS7  MRT   NS   None
4         REDHILL  EW18  MRT   EW   None

In [47]:
df_stations['serial'] = df_stations['code'].map(lambda code : int(re.findall('[0-9]+', code)[0]))

In [48]:
df_stations.head()

             name  code type line  serial
0           EUNOS   EW7  MRT   EW       7
1  CHINESE GARDEN  EW25  MRT   EW      25
2          KHATIB  NS14  MRT   NS      14
3          KRANJI   NS7  MRT   NS       7
4         REDHILL  EW18  MRT   EW      18

In [49]:
df_stations.to_csv('processed_stations.csv', index=False)

In [80]:
class Station:
    def __init__(self, code, name, line, serial):
        self.code = code
        self.name = name
        self.line = line
        self.serial = serial
        self.connections = {}
    def connect(self, code, duration):
        if code in self.connections:
            return
        self.connections[code] = duration
    def __str__(self):
        s = self.name + ", " + self.code
        for con in self.connections:
            s += " [" + con + ": " + str(self.connections[con]) + "] "
        return s

In [81]:
stations = {}

In [82]:
for line in df_stations.values:
    stations[line[1]] = Station(line[1], line[0], line[3], line[4])

In [83]:
import random

In [84]:
for code in stations:
    station = stations[code]
    next_st = station.line + str(station.serial+1)
    prev_st = station.line + str(station.serial-1)
    if next_st in stations:
        duration = random.randint(3, 7)
        station.connect(next_st, duration)
        stations[next_st].connect(station.code, duration)
    if prev_st in stations:
        duration = random.randint(3, 7)
        station.connect(prev_st, duration)
        stations[prev_st].connect(station.code, duration)
    # Find all stations with same name
    for code2 in stations:
        station2 = stations[code2]
        if station.name == station2.name and station.code != station2.code:
            station.connect(station2.code, 5)
            station2.connect(station.code, 5)

In [85]:
for code in stations:
    print(stations[code])

EUNOS, EW7 [EW8: 4]  [EW6: 4]
CHINESE GARDEN, EW25 [EW26: 7]  [EW24: 7]
KHATIB, NS14 [NS15: 6]  [NS13: 4]
KRANJI, NS7 [NS8: 3]
REDHILL, EW18 [EW19: 6]  [EW17: 6]
YEW TEE, NS5 [NS4: 7]
PIONEER, EW28 [EW29: 6]  [EW27: 7]
COMMONWEALTH, EW20 [EW21: 7]  [EW19: 3]
PAYA LEBAR, EW8 [EW7: 4]  [EW9: 6]  [CC9: 5]
PAYA LEBAR, CC9 [EW8: 5]  [CC10: 4]  [CC8: 7]
SIMEI, EW3 [EW4: 3]  [EW2: 6]
TAMPINES, EW2 [EW3: 6]  [EW1: 3]  [DT32: 5]
TAMPINES, DT32 [EW2: 5]  [DT33: 4]  [DT31: 6]
ADMIRALTY, NS10 [NS11: 7]  [NS9: 5]
YISHUN, NS13 [NS14: 4]  [NS12: 4]
PASIR RIS, EW1 [EW2: 3]
CLEMENTI, EW23 [EW24: 7]  [EW22: 6]
ALJUNIED, EW9 [EW8: 6]  [EW10: 3]
ANG MO KIO, NS16 [NS17: 3]  [NS15: 7]
EXPO, CG1 [CG2: 5]  [DT35: 5]
EXPO, DT35 [CG1: 5]  [DT34: 4]
CHOA CHU KANG, NS4 [NS5: 7]  [NS3: 5]
JURONG EAST, EW24 [EW25: 7]  [EW23: 7]  [NS1: 5]
JURONG EAST, NS1 [EW24: 5]  [NS2: 6]
QUEENSTOWN, EW19 [EW18: 6]  [EW20: 3]
TUAS LINK, EW33 [EW32: 7]
GUL CIRCLE, EW30 [EW31: 4]  [EW29: 5]
WOODLANDS, NS9 [NS10: 5]  [NS8: 6]  [TE2: 5]
WOODLANDS, TE2 [NS9: 5]  [TE3: 5]  [TE1: 7]
TUAS CRESCENT, EW31 [EW30: 4]  [EW32: 5]
KALLANG, EW10 [EW9: 3]  [EW11: 6]
TUAS WEST ROAD, EW32 [EW33: 7]  [EW31: 5]
BUONA VISTA, EW21 [EW20: 7]  [EW22: 3]  [CC22: 5]
BUONA VISTA, CC22 [EW21: 5]  [CC23: 5]  [CC21: 5]
DOVER, EW22 [EW23: 6]  [EW21: 3]
SEMBAWANG, NS11 [NS10: 7]  [NS12: 7]
KEMBANGAN, EW6 [EW7: 4]  [EW5: 5]
BUKIT BATOK, NS2 [NS1: 6]  [NS3: 6]
BOON LAY, EW27 [EW28: 7]  [EW26: 5]
BUKIT GOMBAK, NS3 [NS4: 5]  [NS2: 6]
MARSILING, NS8 [NS7: 3]  [NS9: 6]
BEDOK, EW5 [EW6: 5]  [EW4: 4]
JOO KOON, EW29 [EW28: 6]  [EW30: 5]
LAKESIDE, EW26 [EW25: 7]  [EW27: 5]
TANAH MERAH, EW4 [EW3: 3]  [EW5: 4]
YIO CHU KANG, NS15 [NS14: 6]  [NS16: 7]
BRAS BASAH, CC2 [CC3: 4]  [CC1: 7]
MACPHERSON, CC10 [CC9: 4]  [CC11: 3]  [DT26: 5]
MACPHERSON, DT26 [CC10: 5]  [DT27: 3]  [DT25: 4]
CITY HALL, EW13 [EW14: 4]  [EW12: 6]  [NS25: 5]
CITY HALL, NS25 [EW13: 5]  [NS26: 3]  [NS24: 3]
TAMPINES EAST, DT33 [DT32: 4]  [DT34: 7]
TAMPINES WEST, DT31 [DT32: 6]  [DT30: 4]
GEYLANG BAHRU, DT24 [DT25: 6]  [DT23: 6]
BENDEMEER, DT23 [DT24: 6]  [DT22: 7]
BENCOOLEN, DT21 [DT22: 5]  [DT20: 5]
HARBOURFRONT, NE1 [CC29: 5]
HARBOURFRONT, CC29 [NE1: 5]  [CC28: 4]
KENT RIDGE, CC24 [CC25: 5]  [CC23: 5]
PUNGGOL, NE17 [NE16: 7]
TANJONG PAGAR, EW15 [EW16: 3]  [EW14: 5]
ONE-NORTH, CC23 [CC22: 5]  [CC24: 5]
STADIUM, CC6 [CC7: 7]  [CC5: 4]
BUGIS, EW12 [EW13: 6]  [EW11: 6]  [DT14: 5]
BUGIS, DT14 [EW12: 5]  [DT15: 3]  [DT13: 7]
SOMERSET, NS23 [NS24: 6]  [NS22: 5]
ORCHARD, NS22 [NS23: 5]  [NS21: 5]  [TE14: 5]
ORCHARD, TE14 [NS22: 5]
JALAN BESAR, DT22 [DT23: 7]  [DT21: 5]
BAYFRONT, DT16 [DT17: 7]  [DT15: 4]  [CE1: 5]
BAYFRONT, CE1 [DT16: 5]  [CE2: 3]
SENGKANG, NE16 [NE17: 7]  [NE15: 6]
BUKIT BROWN, CC18 [CC19: 6]  [CC17: 3]
MOUNTBATTEN, CC7 [CC6: 7]  [CC8: 6]
KOVAN, NE13 [NE14: 7]  [NE12: 5]
FORT CANNING, DT20 [DT21: 5]  [DT19: 6]
FARRER ROAD, CC20 [CC21: 6]  [CC19: 5]
DOWNTOWN, DT17 [DT16: 7]  [DT18: 7]
ESPLANADE, CC3 [CC2: 4]  [CC4: 5]
NICOLL HIGHWAY, CC5 [CC6: 4]  [CC4: 7]
CALDECOTT, CC17 [CC18: 3]  [CC16: 5]  [TE9: 5]
CALDECOTT, TE9 [CC17: 5]  [TE8: 7]
MARINA BAY, NS27 [NS28: 4]  [NS26: 5]  [TE20: 5]  [CE2: 5]
MARINA BAY, TE20 [NS27: 5]  [CE2: 5]
MARINA BAY, CE2 [CE1: 3]  [NS27: 5]  [TE20: 5]
LABRADOR PARK, CC27 [CC28: 6]  [CC26: 3]
CHINATOWN, NE4 [NE5: 7]  [DT19: 5]
CHINATOWN, DT19 [DT20: 6]  [NE4: 5]  [DT18: 6]
TAN KAH KEE, DT8 [DT9: 7]  [DT7: 6]
TIONG BAHRU, EW17 [EW18: 6]  [EW16: 3]
HILLVIEW, DT3 [DT4: 6]  [DT2: 6]
KING ALBERT PARK, DT6 [DT7: 3]  [DT5: 4]
MATTAR, DT25 [DT26: 4]  [DT24: 6]
UBI, DT27 [DT26: 3]  [DT28: 3]
BEAUTY WORLD, DT5 [DT6: 4]  [DT4: 5]
KAKI BUKIT, DT28 [DT27: 3]  [DT29: 3]
BEDOK NORTH, DT29 [DT28: 3]  [DT30: 6]
DHOBY GHAUT, NS24 [NS25: 3]  [NS23: 6]  [NE6: 5]  [CC1: 5]
DHOBY GHAUT, NE6 [NS24: 5]  [NE7: 4]  [NE5: 7]  [CC1: 5]
DHOBY GHAUT, CC1 [CC2: 7]  [NS24: 5]  [NE6: 5]
WOODLEIGH, NE11 [NE12: 5]  [NE10: 3]
NOVENA, NS20 [NS21: 5]  [NS19: 3]
SERANGOON, NE12 [NE13: 5]  [NE11: 5]  [CC13: 5]
SERANGOON, CC13 [NE12: 5]  [CC14: 4]  [CC12: 5]
BEDOK RESERVOIR, DT30 [DT31: 4]  [DT29: 6]
MARINA SOUTH PIER, NS28 [NS27: 4]
FARRER PARK, NE8 [NE9: 4]  [NE7: 7]
BARTLEY, CC12 [CC13: 5]  [CC11: 7]
DAKOTA, CC8 [CC9: 7]  [CC7: 6]
PASIR PANJANG, CC26 [CC27: 3]  [CC25: 3]
CLARKE QUAY, NE5 [NE4: 7]  [NE6: 7]
BISHAN, NS17 [NS16: 3]  [NS18: 5]  [CC15: 5]
BISHAN, CC15 [NS17: 5]  [CC16: 6]  [CC14: 6]
MARYMOUNT, CC16 [CC17: 5]  [CC15: 6]
HAW PAR VILLA, CC25 [CC24: 5]  [CC26: 3]
LORONG CHUAN, CC14 [CC13: 4]  [CC15: 6]
LAVENDER, EW11 [EW10: 6]  [EW12: 6]
TAI SENG, CC11 [CC10: 3]  [CC12: 7]
ROCHOR, DT13 [DT14: 7]  [DT12: 3]
LITTLE INDIA, NE7 [NE6: 4]  [NE8: 7]  [DT12: 5]
LITTLE INDIA, DT12 [DT13: 3]  [NE7: 5]  [DT11: 5]
STEVENS, DT10 [DT11: 6]  [DT9: 3]  [TE11: 5]
STEVENS, TE11 [DT10: 5]
BUKIT PANJANG, DT1 [DT2: 3]
CASHEW, DT2 [DT3: 6]  [DT1: 3]
SIXTH AVENUE, DT7 [DT8: 6]  [DT6: 3]
TOA PAYOH, NS19 [NS20: 3]  [NS18: 7]
WOODLANDS SOUTH, TE3 [TE2: 5]  [TE4: 4]
POTONG PASIR, NE10 [NE11: 3]  [NE9: 6]
HOUGANG, NE14 [NE13: 7]  [NE15: 7]
BOON KENG, NE9 [NE8: 4]  [NE10: 6]
UPPER CHANGI, DT34 [DT35: 4]  [DT33: 7]
CHANGI AIRPORT, CG2 [CG1: 5]
BRADDELL, NS18 [NS17: 5]  [NS19: 7]
BUANGKOK, NE15 [NE16: 6]  [NE14: 7]
PROMENADE, CC4 [CC3: 5]  [CC5: 7]  [DT15: 5]
PROMENADE, DT15 [DT14: 3]  [DT16: 4]  [CC4: 5]
BOTANIC GARDENS, CC19 [CC18: 6]  [CC20: 5]  [DT9: 5]
BOTANIC GARDENS, DT9 [DT8: 7]  [DT10: 3]  [CC19: 5]
RAFFLES PLACE, EW14 [EW13: 4]  [EW15: 5]  [NS26: 5]
RAFFLES PLACE, NS26 [NS25: 3]  [NS27: 5]  [EW14: 5]
HOLLAND VILLAGE, CC21 [CC22: 5]  [CC20: 6]
OUTRAM PARK, EW16 [EW15: 3]  [EW17: 3]
TELOK BLANGAH, CC28 [CC29: 4]  [CC27: 6]
TELOK AYER, DT18 [DT17: 7]  [DT19: 6]
NEWTON, NS21 [NS22: 5]  [NS20: 5]  [DT11: 5]
NEWTON, DT11 [DT12: 5]  [DT10: 6]  [NS21: 5]
CANBERRA, NS12 [NS13: 4]  [NS11: 7]
WOODLANDS NORTH, TE1 [TE2: 7]
HUME, DT4 [DT3: 6]  [DT5: 5]
SPRINGLEAF, TE4 [TE3: 4]  [TE5: 7]
LENTOR, TE5 [TE4: 7]  [TE6: 5]
MAYFLOWER, TE6 [TE5: 5]  [TE7: 5]
BRIGHT HILL, TE7 [TE6: 5]  [TE8: 5]
UPPER THOMSON, TE8 [TE9: 7]  [TE7: 5]